include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    
analyzer:
  errors:
    sort_unnamed_constructors_first: ignore
  exclude:
    - lib/**.gen.dart
  plugins:
    - data_class_plugin
