name: lectio_plus_plus
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  lectio_wrapper: ^0.7.4
  data_class_plugin: any
  fuzzy: ^0.5.1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0
  flutter_secure_storage: ^9.2.4
  eva_icons_flutter: ^3.1.0
  get_it: ^7.6.0
  syncfusion_flutter_calendar: ^29.2.8
  syncfusion_flutter_core: ^29.2.9
  auto_route: ^9.3.0+1
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.15
  build_verify: any
  tachyon: any
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/illustrations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Fraunces
      fonts:
        - asset: assets/fonts/fraunces.ttf