name: lectio_plus_plus

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ANDROID_KEYSTORE_PATH: "keystore/keystore.jks"
  ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
  ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    runs-on: macos-latest
    permissions:
      contents: write
    environment: PRODUCTION
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.29.3
          cache: true
          cache-sdk: true
      - run: flutter pub get
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore.jks'
          fileDir: 'keystore/'
          encodedString: ${{ secrets.KEYSTORE }}
      #- run: flutter test
      - run: flutter build apk --flavor production --target lib/main_production.dart --build-number ${{github.run_number}}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
      - uses: actions/checkout@v4

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
